name: PR healthier

on: [pull_request]

jobs:
  check-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 18.x

    - name: Install packages
      run: yarn

    - name: Run Tests
      run: yarn test

    - name: Run Code Formatter (optional)
      run: yarn format:check
